{% set name = "WDL-AID" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 2cafbf2f35c2f90eb49571441904b42dfe16fb4e81b8062228dae2290fb276a2

build:
  noarch: python
  number: 0
  entry_points:
    - wdl-aid=wdl_aid.wdl_aid:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.6
    - setuptools
  run:
    - jinja2
    - miniwdl >=1.0
    - python >=3.6
    - setuptools

test:
  imports:
    - wdl_aid
    - wdl_aid.templates
  commands:
    - wdl-aid --help
  requires:
    - python 3.6

about:
  home: https://github.com/biowdl/wdl-aid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Input Documentation for WDL workflows
  doc_url: https://wdl-aid.readthedocs.io/

extra:
  recipe-maintainers:
    - DavyCats
    - rhpvorderman
